version: '3.7'

networks:
  dev_env:
    external: true

services:
  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - web:/var/www
      - $PWD/docker/php/config/php-config.ini:/usr/local/etc/php/conf.d/php-config.ini
    depends_on:
      - mysql
    working_dir: /var/www
    networks:
      - dev_env
    ports:
      - '9000:80'
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - nginx-conf:/etc/nginx/conf.d/
      - web:/var/www
    ports:
      - '5010:80'
    depends_on:
      - php
    networks:
      - dev_env
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - '5012:3306'
    env_file: .env
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql/
    networks:
      - dev_env
  encore:
    container_name: encore
    volumes:
      - web:/usr/src/app
    build:
      context: ./docker/node/
      dockerfile: Dockerfile
    working_dir: /usr/src/app/
    command: ["yarn", "run", "dev"]
    networks:
      - dev_env

volumes:
  web:
  nginx-conf:
  mysql:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
      configurationBeta:
        permissions:
          defaultOwner: "id:1111"
          defaultGroup: "id:1111"
          defaultFileMode: "0666"
          defaultDirectoryMode: "0666"
    web:
      alpha: "./www"
      beta: "volume://web"
      ignore:
        paths:
          - "vendor"
          - "var"
    nginx-conf:
      alpha: "./docker/nginx"
      beta: "volume://nginx-conf"
    mysql:
      alpha: "./database"
      beta: "volume://mysql"